# Generated by Django 5.2.7 on 2025-11-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsmodel",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productsmodel",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productsmodel",
            name="title_en",
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productsmodel",
            name="title_uz",
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
