# Generated by Django 5.2.7 on 2025-11-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productsmodel_description_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsmodel",
            name="image",
        ),
    ]
