# Generated by Django 5.2.7 on 2025-10-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_device_device_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_identified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='one_id_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='one_id_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_serial',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sess_id',
        ),
    ]
