# Generated by Django 5.2.7 on 2025-10-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_identified_remove_user_one_id_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='device',
            name='device_token_active_idx',
        ),
        migrations.RemoveField(
            model_name='device',
            name='refresh_token_jti',
        ),
    ]
