# Generated by Django 5.2.7 on 2025-10-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_device_device_token_active_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique device identifier",
                max_length=255,
                unique=True,
            ),
        ),
    ]
