# Generated by Django 5.2.7 on 2025-11-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipemodel",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="recipemodel",
            name="description_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="recipemodel",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipemodel",
            name="title_uz",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
